name : portfolio-test

on: 
  push:
    branch:
      - dev

jobs: 
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22.3.0
    steps:
      - uses: actions/checkout@v3
        with:
        node-version: 22.3.0
      - run: npm ci
      - run: npm run test